/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIsta;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JToolBar;

/**
 *
 * @author Abel Gomez
 */
public class vistamenuprincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistamenuprincipal
     */
    public vistamenuprincipal() {
        initComponents();
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }
    

    public JButton getBtncrudclientes() {
        return btncrudclientes;
    }

    public void setBtncrudclientes(JButton btncrudclientes) {
        this.btncrudclientes = btncrudclientes;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    public JDesktopPane getJdpprincipal() {
        return jdpprincipal;
    }

    public void setJdpprincipal(JDesktopPane jdpprincipal) {
        this.jdpprincipal = jdpprincipal;
    }

    public JButton getBtncrudproveedores() {
        return btncrudproveedores;
    }

    public void setBtncrudproveedores(JButton btncrudproveedores) {
        this.btncrudproveedores = btncrudproveedores;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btncrudclientes = new javax.swing.JButton();
        btncrudproveedores = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jdpprincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        btncrudclientes.setText("Cliente");
        btncrudclientes.setFocusable(false);
        btncrudclientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncrudclientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncrudclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrudclientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btncrudclientes);

        btncrudproveedores.setText("Proveedor");
        btncrudproveedores.setFocusable(false);
        btncrudproveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncrudproveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncrudproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrudproveedoresActionPerformed(evt);
            }
        });
        jToolBar1.add(btncrudproveedores);

        jButton1.setText("Productos");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 280, 70));

        jdpprincipal.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jdpprincipalLayout = new javax.swing.GroupLayout(jdpprincipal);
        jdpprincipal.setLayout(jdpprincipalLayout);
        jdpprincipalLayout.setHorizontalGroup(
            jdpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        jdpprincipalLayout.setVerticalGroup(
            jdpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        getContentPane().add(jdpprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1210, 720));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncrudclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrudclientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncrudclientesActionPerformed

    private void btncrudproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrudproveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncrudproveedoresActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(vistamenuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(vistamenuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(vistamenuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(vistamenuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new vistamenuprincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncrudclientes;
    private javax.swing.JButton btncrudproveedores;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDesktopPane jdpprincipal;
    // End of variables declaration//GEN-END:variables
}
